[
  {
    "id": 1,
    "name": "LeBron James",
    "team": "Lakers",
    "conference": "West",
    "position": "SF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png",
    "number": 23,
    "height_cm": 206,
    "weight_kg": 113,
    "age": 41
  },
  {
    "id": 2,
    "name": "Stephen Curry",
    "team": "Warriors",
    "conference": "West",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png",
    "number": 30,
    "height_cm": 188,
    "weight_kg": 84,
    "age": 38
  },
  {
    "id": 3,
    "name": "Kevin Durant",
    "team": "Suns",
    "conference": "West",
    "position": "PF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
    "number": 35,
    "height_cm": 211,
    "weight_kg": 109,
    "age": 37
  },
  {
    "id": 4,
    "name": "Nikola Jokic",
    "team": "Nuggets",
    "conference": "West",
    "position": "C",
    "country": "Serbia",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/203999.png",
    "number": 15,
    "height_cm": 211,
    "weight_kg": 129,
    "age": 31
  },
  {
    "id": 5,
    "name": "Giannis Antetokounmpo",
    "team": "Bucks",
    "conference": "East",
    "position": "PF",
    "country": "Greece",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png",
    "number": 34,
    "height_cm": 211,
    "weight_kg": 110,
    "age": 31
  },
  {
    "id": 6,
    "name": "Victor Wembanyama",
    "team": "Spurs",
    "conference": "West",
    "position": "C",
    "country": "France",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1641705.png",
    "number": 1,
    "height_cm": 224,
    "weight_kg": 95,
    "age": 22
  },
  {
    "id": 7,
    "name": "Luka Doncic",
    "team": "Lakers",
    "conference": "West",
    "position": "PG",
    "country": "Slovenia",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png",
    "number": 77,
    "height_cm": 201,
    "weight_kg": 104,
    "age": 27
  },
  {
    "id": 8,
    "name": "Jayson Tatum",
    "team": "Celtics",
    "conference": "East",
    "position": "SF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
    "number": 0,
    "height_cm": 203,
    "weight_kg": 95,
    "age": 28
  },
  {
    "id": 9,
    "name": "Shai Gilgeous-Alexander",
    "team": "Thunder",
    "conference": "West",
    "position": "SG",
    "country": "Canada",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628983.png",
    "number": 2,
    "height_cm": 198,
    "weight_kg": 82,
    "age": 27
  },
  {
    "id": 10,
    "name": "Anthony Edwards",
    "team": "Timberwolves",
    "conference": "West",
    "position": "SG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630162.png",
    "number": 5,
    "height_cm": 193,
    "weight_kg": 102,
    "age": 24
  },
  {
    "id": 11,
    "name": "Joel Embiid",
    "team": "76ers",
    "conference": "East",
    "position": "C",
    "country": "Cameroon",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png",
    "number": 21,
    "height_cm": 213,
    "weight_kg": 127,
    "age": 32
  },
  {
    "id": 12,
    "name": "Ja Morant",
    "team": "Grizzlies",
    "conference": "West",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1629630.png",
    "number": 12,
    "height_cm": 188,
    "weight_kg": 79,
    "age": 27
  },
  {
    "id": 13,
    "name": "Damian Lillard",
    "team": "Bucks",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/203081.png",
    "number": 0,
    "height_cm": 188,
    "weight_kg": 88,
    "age": 36
  },
  {
    "id": 14,
    "name": "Kawhi Leonard",
    "team": "Clippers",
    "conference": "West",
    "position": "SF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/202695.png",
    "number": 2,
    "height_cm": 201,
    "weight_kg": 102,
    "age": 35
  },
  {
    "id": 15,
    "name": "Paul George",
    "team": "76ers",
    "conference": "East",
    "position": "SF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/202331.png",
    "number": 8,
    "height_cm": 203,
    "weight_kg": 100,
    "age": 36
  },
  {
    "id": 16,
    "name": "Devin Booker",
    "team": "Suns",
    "conference": "West",
    "position": "SG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1626164.png",
    "number": 1,
    "height_cm": 198,
    "weight_kg": 93,
    "age": 30
  },
  {
    "id": 17,
    "name": "Trae Young",
    "team": "Hawks",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1629027.png",
    "number": 11,
    "height_cm": 185,
    "weight_kg": 74,
    "age": 28
  },
  {
    "id": 18,
    "name": "Donovan Mitchell",
    "team": "Cavaliers",
    "conference": "East",
    "position": "SG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628378.png",
    "number": 45,
    "height_cm": 191,
    "weight_kg": 98,
    "age": 30
  },
  {
    "id": 19,
    "name": "Tyrese Haliburton",
    "team": "Pacers",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630169.png",
    "number": 0,
    "height_cm": 196,
    "weight_kg": 84,
    "age": 26
  },
  {
    "id": 20,
    "name": "Zion Williamson",
    "team": "Pelicans",
    "conference": "West",
    "position": "PF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1629627.png",
    "number": 1,
    "height_cm": 198,
    "weight_kg": 129,
    "age": 26
  },
  {
    "id": 21,
    "name": "Jimmy Butler",
    "team": "Warriors",
    "conference": "West",
    "position": "SF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/202710.png",
    "number": 10,
    "height_cm": 201,
    "weight_kg": 104,
    "age": 37
  },
  {
    "id": 22,
    "name": "Bam Adebayo",
    "team": "Heat",
    "conference": "East",
    "position": "C",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628389.png",
    "number": 13,
    "height_cm": 206,
    "weight_kg": 116,
    "age": 29
  },
  {
    "id": 23,
    "name": "Jaylen Brown",
    "team": "Celtics",
    "conference": "East",
    "position": "SG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1627759.png",
    "number": 7,
    "height_cm": 198,
    "weight_kg": 101,
    "age": 30
  },
  {
    "id": 24,
    "name": "Kyrie Irving",
    "team": "Mavericks",
    "conference": "West",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/202681.png",
    "number": 11,
    "height_cm": 188,
    "weight_kg": 88,
    "age": 34
  },
  {
    "id": 25,
    "name": "Anthony Davis",
    "team": "Mavericks",
    "conference": "West",
    "position": "C",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png",
    "number": 3,
    "height_cm": 208,
    "weight_kg": 115,
    "age": 33
  },
  {
    "id": 26,
    "name": "De'Aaron Fox",
    "team": "Spurs",
    "conference": "West",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628368.png",
    "number": 4,
    "height_cm": 191,
    "weight_kg": 84,
    "age": 29
  },
  {
    "id": 27,
    "name": "Domantas Sabonis",
    "team": "Kings",
    "conference": "West",
    "position": "C",
    "country": "Lithuania",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1627734.png",
    "number": 11,
    "height_cm": 208,
    "weight_kg": 109,
    "age": 30
  },
  {
    "id": 28,
    "name": "Jalen Brunson",
    "team": "Knicks",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628973.png",
    "number": 11,
    "height_cm": 188,
    "weight_kg": 86,
    "age": 30
  },
  {
    "id": 29,
    "name": "Karl-Anthony Towns",
    "team": "Knicks",
    "conference": "East",
    "position": "C",
    "country": "Dominican Republic",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1626157.png",
    "number": 32,
    "height_cm": 213,
    "weight_kg": 112,
    "age": 31
  },
  {
    "id": 30,
    "name": "Rudy Gobert",
    "team": "Timberwolves",
    "conference": "West",
    "position": "C",
    "country": "France",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/203497.png",
    "number": 27,
    "height_cm": 216,
    "weight_kg": 117,
    "age": 34
  },
  {
    "id": 31,
    "name": "Evan Fournier",
    "team": "Pistons",
    "conference": "East",
    "position": "SG",
    "country": "France",
    "number": 31,
    "height_cm": 198,
    "weight_kg": 93,
    "age": 34
  },
  {
    "id": 32,
    "name": "Alperen Sengun",
    "team": "Rockets",
    "conference": "West",
    "position": "C",
    "country": "Turkey",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630578.png",
    "number": 28,
    "height_cm": 211,
    "weight_kg": 110,
    "age": 24
  },
  {
    "id": 33,
    "name": "Franz Wagner",
    "team": "Magic",
    "conference": "East",
    "position": "SF",
    "country": "Germany",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630532.png",
    "number": 22,
    "height_cm": 208,
    "weight_kg": 100,
    "age": 25
  },
  {
    "id": 34,
    "name": "Paolo Banchero",
    "team": "Magic",
    "conference": "East",
    "position": "PF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1631094.png",
    "number": 5,
    "height_cm": 208,
    "weight_kg": 113,
    "age": 24
  },
  {
    "id": 35,
    "name": "Cade Cunningham",
    "team": "Pistons",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630595.png",
    "number": 2,
    "height_cm": 198,
    "weight_kg": 100,
    "age": 25
  },
  {
    "id": 36,
    "name": "Tyrese Maxey",
    "team": "76ers",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630178.png",
    "number": 0,
    "height_cm": 188,
    "weight_kg": 91,
    "age": 26
  },
  {
    "id": 37,
    "name": "LaMelo Ball",
    "team": "Hornets",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630163.png",
    "number": 1,
    "height_cm": 201,
    "weight_kg": 82,
    "age": 25
  },
  {
    "id": 38,
    "name": "Jarrett Allen",
    "team": "Cavaliers",
    "conference": "East",
    "position": "C",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628386.png",
    "number": 31,
    "height_cm": 206,
    "weight_kg": 110,
    "age": 28
  },
  {
    "id": 39,
    "name": "Pascal Siakam",
    "team": "Pacers",
    "conference": "East",
    "position": "PF",
    "country": "Cameroon",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1627783.png",
    "number": 43,
    "height_cm": 203,
    "weight_kg": 104,
    "age": 32
  },
  {
    "id": 40,
    "name": "Kristaps Porzingis",
    "team": "Celtics",
    "conference": "East",
    "position": "C",
    "country": "Latvia",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/204001.png",
    "number": 8,
    "height_cm": 221,
    "weight_kg": 109,
    "age": 31
  },
  {
    "id": 41,
    "name": "Jrue Holiday",
    "team": "Celtics",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/201950.png",
    "number": 4,
    "height_cm": 193,
    "weight_kg": 93,
    "age": 36
  },
  {
    "id": 42,
    "name": "Jamal Murray",
    "team": "Nuggets",
    "conference": "West",
    "position": "PG",
    "country": "Canada",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1627750.png",
    "number": 27,
    "height_cm": 193,
    "weight_kg": 98,
    "age": 29
  },
  {
    "id": 43,
    "name": "Aaron Gordon",
    "team": "Nuggets",
    "conference": "West",
    "position": "PF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/203932.png",
    "number": 32,
    "height_cm": 203,
    "weight_kg": 107,
    "age": 31
  },
  {
    "id": 44,
    "name": "Darius Garland",
    "team": "Cavaliers",
    "conference": "East",
    "position": "PG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1629636.png",
    "number": 10,
    "height_cm": 185,
    "weight_kg": 87,
    "age": 26
  },
  {
    "id": 45,
    "name": "Jaren Jackson Jr.",
    "team": "Grizzlies",
    "conference": "West",
    "position": "PF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628991.png",
    "number": 13,
    "height_cm": 208,
    "weight_kg": 109,
    "age": 27
  },
  {
    "id": 46,
    "name": "Brandon Ingram",
    "team": "Raptors",
    "conference": "East",
    "position": "SF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1627742.png",
    "number": 3,
    "height_cm": 203,
    "weight_kg": 86,
    "age": 29
  },
  {
    "id": 47,
    "name": "Mikal Bridges",
    "team": "Knicks",
    "conference": "East",
    "position": "SF",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628969.png",
    "number": 25,
    "height_cm": 198,
    "weight_kg": 95,
    "age": 30
  },
  {
    "id": 48,
    "name": "OG Anunoby",
    "team": "Knicks",
    "conference": "East",
    "position": "SF",
    "country": "United Kingdom",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628384.png",
    "number": 8,
    "height_cm": 201,
    "weight_kg": 105,
    "age": 29
  },
  {
    "id": 49,
    "name": "Chet Holmgren",
    "team": "Thunder",
    "conference": "West",
    "position": "C",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1631096.png",
    "number": 7,
    "height_cm": 216,
    "weight_kg": 94,
    "age": 24
  },
  {
    "id": 50,
    "name": "Amen Thompson",
    "team": "Rockets",
    "conference": "West",
    "position": "SG",
    "country": "USA",
    "image": "https://cdn.nba.com/headshots/nba/latest/1040x760/1641708.png",
    "number": 1,
    "height_cm": 201,
    "weight_kg": 98,
    "age": 23
  }
]